// Code generated by FastPB v0.0.1. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

func (x *CreateConfigReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateConfigReq[number], err)
}

func (x *CreateConfigReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Namespace, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateConfigReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Group, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateConfigReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Filename, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CreateConfigReply) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CreateConfigReply[number], err)
}

func (x *CreateConfigReply) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Code, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *CreateConfigReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *CreateConfigReq) fastWriteField1(buf []byte) (offset int) {
	if x.Namespace == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.Namespace)
	return offset
}

func (x *CreateConfigReq) fastWriteField2(buf []byte) (offset int) {
	if x.Group == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.Group)
	return offset
}

func (x *CreateConfigReq) fastWriteField3(buf []byte) (offset int) {
	if x.Filename == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.Filename)
	return offset
}

func (x *CreateConfigReply) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *CreateConfigReply) fastWriteField1(buf []byte) (offset int) {
	if x.Code == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, x.Code)
	return offset
}

func (x *CreateConfigReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *CreateConfigReq) sizeField1() (n int) {
	if x.Namespace == "" {
		return n
	}
	n += fastpb.SizeString(1, x.Namespace)
	return n
}

func (x *CreateConfigReq) sizeField2() (n int) {
	if x.Group == "" {
		return n
	}
	n += fastpb.SizeString(2, x.Group)
	return n
}

func (x *CreateConfigReq) sizeField3() (n int) {
	if x.Filename == "" {
		return n
	}
	n += fastpb.SizeString(3, x.Filename)
	return n
}

func (x *CreateConfigReply) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *CreateConfigReply) sizeField1() (n int) {
	if x.Code == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, x.Code)
	return n
}

var fieldIDToName_CreateConfigReq = map[int32]string{
	1: "Namespace",
	2: "Group",
	3: "Filename",
}

var fieldIDToName_CreateConfigReply = map[int32]string{
	1: "Code",
}
