// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: idl/config/config.proto

package api

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group     string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Filename  string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *CreateConfigReq) Reset() {
	*x = CreateConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_config_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigReq) ProtoMessage() {}

func (x *CreateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_config_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigReq.ProtoReflect.Descriptor instead.
func (*CreateConfigReq) Descriptor() ([]byte, []int) {
	return file_idl_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConfigReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateConfigReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateConfigReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type CreateConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateConfigReply) Reset() {
	*x = CreateConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_config_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigReply) ProtoMessage() {}

func (x *CreateConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_config_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigReply.ProtoReflect.Descriptor instead.
func (*CreateConfigReply) Descriptor() ([]byte, []int) {
	return file_idl_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConfigReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_idl_config_config_proto protoreflect.FileDescriptor

var file_idl_config_config_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x61,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x46, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x3c, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x6f, 0x67, 0x65, 0x72, 0x6f, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_config_config_proto_rawDescOnce sync.Once
	file_idl_config_config_proto_rawDescData = file_idl_config_config_proto_rawDesc
)

func file_idl_config_config_proto_rawDescGZIP() []byte {
	file_idl_config_config_proto_rawDescOnce.Do(func() {
		file_idl_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_config_config_proto_rawDescData)
	})
	return file_idl_config_config_proto_rawDescData
}

var file_idl_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idl_config_config_proto_goTypes = []interface{}{
	(*CreateConfigReq)(nil),   // 0: api.CreateConfigReq
	(*CreateConfigReply)(nil), // 1: api.CreateConfigReply
}
var file_idl_config_config_proto_depIdxs = []int32{
	0, // 0: api.Config.CreateConfig:input_type -> api.CreateConfigReq
	1, // 1: api.Config.CreateConfig:output_type -> api.CreateConfigReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_config_config_proto_init() }
func file_idl_config_config_proto_init() {
	if File_idl_config_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_config_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_config_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_config_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_config_config_proto_goTypes,
		DependencyIndexes: file_idl_config_config_proto_depIdxs,
		MessageInfos:      file_idl_config_config_proto_msgTypes,
	}.Build()
	File_idl_config_config_proto = out.File
	file_idl_config_config_proto_rawDesc = nil
	file_idl_config_config_proto_goTypes = nil
	file_idl_config_config_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.4.2. DO NOT EDIT.

type Config interface {
	CreateConfig(ctx context.Context, req *CreateConfigReq) (res *CreateConfigReply, err error)
}
